CREATE TABLE IF NOT EXISTS TB_BOARD (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content VARCHAR(2000),
    author VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS TB_USER (
    userId VARCHAR(100) PRIMARY KEY,
    passwd VARCHAR(255) NOT NULL,
    userName VARCHAR(2000),
    role VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS TB_WORK_TASK (
    task_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content VARCHAR(2000),
    status VARCHAR(30) NOT NULL,
    priority VARCHAR(20) NOT NULL,
    due_date DATE,
    created_by VARCHAR(100) NOT NULL,
    assigned_to VARCHAR(100),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT FK_WORK_TASK_CREATED_BY
        FOREIGN KEY (created_by) REFERENCES TB_USER(userId),
    CONSTRAINT FK_WORK_TASK_ASSIGNED_TO
        FOREIGN KEY (assigned_to) REFERENCES TB_USER(userId)
);

CREATE TABLE IF NOT EXISTS TB_TASK_HISTORY (
    history_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    task_id BIGINT NOT NULL,
    before_status VARCHAR(30),
    after_status VARCHAR(30) NOT NULL,
    changed_by VARCHAR(100) NOT NULL,
    comment VARCHAR(1000),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT FK_TASK_HISTORY_TASK
        FOREIGN KEY (task_id) REFERENCES TB_WORK_TASK(task_id),
    CONSTRAINT FK_TASK_HISTORY_CHANGED_BY
        FOREIGN KEY (changed_by) REFERENCES TB_USER(userId)
);
