CREATE TABLE IF NOT EXISTS TB_BOARD (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content VARCHAR(2000),
    author VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS TB_USER (
    userId VARCHAR(100) PRIMARY KEY,
    passwd VARCHAR(255) NOT NULL,
    userName VARCHAR(2000),
    role VARCHAR(20)
);
